### ISSUE TITLE
批量功能不生效

### ISSUE THREAD

**Issue by AWDSCAN** [qi4L/WeblogicScan.go#3]
感谢大佬百忙之中的回应，这边我刚刚看到，我下载releases最新版，但是releases的批量功能是不生效的

**Comment by qi4L** [comment]
![image](https://github.com/qi4L/WeblogicScan.go/assets/75202638/14e49880-ccad-4155-b223-b36ae39f3afb)

**Comment by qi4L** [comment]
我用着没问题啊

**Comment by AWDSCAN** [comment]
> 我用着没问题啊

我用的Linux版本没起作用，我没指定端口，我的目标文件里面有一些是自带了端口，不会是这个原因吧

**Comment by qi4L** [comment]
我改下

**Comment by qi4L** [comment]
等1.3打包好了，就OK了
